#!/usr/bin/env python3
"""
Rebuilds the 'Calendar' tab of 'Manpower Loading Template.xlsx' from the
'Input' tab: straight-line spreads each row's Baseline Hours and Baseline
Qty across its Start -> Finish window into weekly buckets running left to
right, then totals Hours/FTE/Qty per week.

Run this after pasting or editing rows on the Input tab:
    python3 scripts/generate_calendar.py "Manpower Loading Template.xlsx"
"""
import datetime
import sys
from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

FONT = "Arial"
f_header    = Font(name=FONT, size=10, bold=True, color="FFFFFF")
f_subheader = Font(name=FONT, size=10, bold=True, color="1F2937")
f_formula   = Font(name=FONT, size=10, color="000000")
f_total     = Font(name=FONT, size=10, bold=True, color="000000")
f_note      = Font(name=FONT, size=9, italic=True, color="595959")

fill_header  = PatternFill("solid", fgColor="1F4E79")
fill_section = PatternFill("solid", fgColor="D9E1F2")
fill_total   = PatternFill("solid", fgColor="EDEDED")

thin = Side(style="thin", color="BFBFBF")
border_all = Border(left=thin, right=thin, top=thin, bottom=thin)


def monday_on_or_before(d):
    return d - datetime.timedelta(days=d.weekday())


def read_input_rows(ws):
    rows = []
    r = 2
    while True:
        commodity = ws.cell(row=r, column=1).value
        qty = ws.cell(row=r, column=2).value
        hours = ws.cell(row=r, column=3).value
        di = ws.cell(row=r, column=5).value
        whc = ws.cell(row=r, column=6).value
        start = ws.cell(row=r, column=7).value
        finish = ws.cell(row=r, column=8).value
        if commodity is None and qty is None and hours is None and start is None and finish is None:
            if r > ws.max_row:
                break
            r += 1
            if r - 2 > 10000:
                break
            continue
        if isinstance(start, datetime.datetime):
            start = start.date()
        if isinstance(finish, datetime.datetime):
            finish = finish.date()
        if commodity and qty is not None and hours is not None and start and finish:
            duration_days = (finish - start).days + 1
            if duration_days > 0:
                rows.append({
                    "row": r,
                    "commodity": commodity,
                    "qty": float(qty),
                    "hours": float(hours),
                    "di": di,
                    "whc": whc,
                    "start": start,
                    "finish": finish,
                    "duration_days": duration_days,
                    "hrs_per_day": float(hours) / duration_days,
                    "qty_per_day": float(qty) / duration_days,
                })
        r += 1
        if r > ws.max_row + 1:
            break
    return rows


def week_overlap_days(row_start, row_finish, week_start):
    week_end = week_start + datetime.timedelta(days=6)
    lo = max(row_start, week_start)
    hi = min(row_finish, week_end)
    return max(0, (hi - lo).days + 1)


def build_calendar(path):
    wb = load_workbook(path)
    input_ws = wb["Input"]
    fte_basis = input_ws["S1"].value or 60

    rows = read_input_rows(input_ws)

    if "Calendar" in wb.sheetnames:
        del wb["Calendar"]
    cal = wb.create_sheet("Calendar")
    cal.sheet_view.showGridLines = False

    cal["A1"] = "Weekly Manpower & Quantity Calendar"
    cal["A1"].font = Font(name=FONT, size=14, bold=True, color="1F4E79")
    cal["A2"] = ("Straight-line spread of each Input row's Baseline Hours / Baseline Qty across its "
                 "Start-Finish window, in weekly buckets left to right. Regenerated by "
                 "scripts/generate_calendar.py — re-run after editing the Input tab.")
    cal["A2"].font = f_note
    cal.merge_cells("A2:H2")

    if not rows:
        cal["A4"] = "No data rows found on the Input tab yet — paste your commodities and re-run this script."
        cal["A4"].font = f_note
        wb.save(path)
        return 0, 0

    earliest_start = min(r["start"] for r in rows)
    latest_finish = max(r["finish"] for r in rows)
    first_week = monday_on_or_before(earliest_start)
    n_weeks = ((latest_finish - first_week).days // 7) + 1
    week_starts = [first_week + datetime.timedelta(days=7 * w) for w in range(n_weeks)]

    HEADER_ROW = 3
    FIRST_WEEK_COL = 3
    cal.cell(row=HEADER_ROW, column=1, value="Commodity").font = f_header
    cal.cell(row=HEADER_ROW, column=2, value="WHC or SUB").font = f_header
    for c in (1, 2):
        cell = cal.cell(row=HEADER_ROW, column=c)
        cell.fill = fill_header
        cell.alignment = Alignment(horizontal="center", vertical="center")
        cell.border = border_all

    for w, wk in enumerate(week_starts):
        col = FIRST_WEEK_COL + w
        cell = cal.cell(row=HEADER_ROW, column=col, value=wk)
        cell.number_format = "mm/dd/yy"
        cell.font = f_header
        cell.fill = fill_header
        cell.alignment = Alignment(horizontal="center")
        cell.border = border_all

    cal.column_dimensions["A"].width = 26
    cal.column_dimensions["B"].width = 12
    for w in range(len(week_starts)):
        cal.column_dimensions[get_column_letter(FIRST_WEEK_COL + w)].width = 9.5

    def write_block(start_row, section_title, value_key, total_label, fte_row=False):
        cal.cell(row=start_row, column=1, value=section_title).font = Font(name=FONT, size=11, bold=True, color="1F4E79")
        cal.merge_cells(start_row=start_row, start_column=1, end_row=start_row, end_column=8)
        cal.cell(row=start_row, column=1).fill = fill_section

        header_row = start_row + 1
        cal.cell(row=header_row, column=1, value="Commodity").font = f_subheader
        cal.cell(row=header_row, column=2, value="WHC or SUB").font = f_subheader
        for w, wk in enumerate(week_starts):
            cell = cal.cell(row=header_row, column=FIRST_WEEK_COL + w, value=wk)
            cell.number_format = "mm/dd/yy"
            cell.font = f_subheader
            cell.alignment = Alignment(horizontal="center")

        data_start = header_row + 1
        week_totals = [0.0] * len(week_starts)
        for i, r in enumerate(rows):
            cal_row = data_start + i
            cal.cell(row=cal_row, column=1, value=r["commodity"]).font = f_formula
            cal.cell(row=cal_row, column=2, value=r["whc"]).font = f_formula
            for w, wk in enumerate(week_starts):
                overlap = week_overlap_days(r["start"], r["finish"], wk)
                value = overlap * r[value_key]
                if value:
                    cell = cal.cell(row=cal_row, column=FIRST_WEEK_COL + w, value=round(value, 2))
                    cell.font = f_formula
                    cell.number_format = "0.0"
                    week_totals[w] += value

        data_end = data_start + len(rows) - 1
        total_row = data_end + 1
        cal.cell(row=total_row, column=1, value=total_label).font = f_total
        cal.merge_cells(start_row=total_row, start_column=1, end_row=total_row, end_column=2)
        for w in range(len(week_starts)):
            cell = cal.cell(row=total_row, column=FIRST_WEEK_COL + w, value=round(week_totals[w], 2))
            cell.font = f_total
            cell.fill = fill_total
            cell.number_format = "0.0"

        next_row = total_row + 1
        if fte_row:
            cal.cell(row=next_row, column=1, value="TOTAL FTE (Hrs/Week / FTE basis)").font = f_total
            cal.merge_cells(start_row=next_row, start_column=1, end_row=next_row, end_column=2)
            for w in range(len(week_starts)):
                fte_val = week_totals[w] / fte_basis if fte_basis else 0
                cell = cal.cell(row=next_row, column=FIRST_WEEK_COL + w, value=round(fte_val, 2))
                cell.font = f_total
                cell.fill = fill_total
                cell.number_format = "0.00"
            next_row += 1
        return next_row + 1

    next_block_row = write_block(
        start_row=HEADER_ROW + 1,
        section_title="HOURS PER WEEK  (Baseline Hours spread straight-line across Start-Finish)",
        value_key="hrs_per_day",
        total_label="TOTAL HOURS / WEEK",
        fte_row=True,
    )
    write_block(
        start_row=next_block_row,
        section_title="QUANTITY PER WEEK  (Baseline Qty spread straight-line across Start-Finish)",
        value_key="qty_per_day",
        total_label="TOTAL QTY / WEEK",
        fte_row=False,
    )

    cal.freeze_panes = "C4"
    wb.save(path)
    return len(rows), len(week_starts)


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "Manpower Loading Template.xlsx"
    n_rows, n_weeks = build_calendar(path)
    print(f"Calendar rebuilt: {n_rows} commodity row(s) x {n_weeks} week(s) -> {path}")
